# Generated by Django 5.0.6 on 2026-04-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='Mã đơn')),
                ('status', models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('processing', 'Đang xử lý'), ('shipped', 'Đang giao'), ('delivered', 'Đã giao'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('payment_method', models.CharField(choices=[('cod', 'Thanh toán khi nhận hàng'), ('bank', 'Chuyển khoản ngân hàng'), ('momo', 'Ví MoMo')], default='cod', max_length=20, verbose_name='Thanh toán')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Đã thanh toán')),
                ('shipping_name', models.CharField(max_length=100, verbose_name='Tên người nhận')),
                ('shipping_phone', models.CharField(max_length=20, verbose_name='SĐT giao hàng')),
                ('shipping_address', models.TextField(verbose_name='Địa chỉ giao hàng')),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('shipping_fee', models.DecimalField(decimal_places=0, default=30000, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Đơn hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_sku', models.CharField(max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Chi tiết đơn hàng',
                'verbose_name_plural': 'Chi tiết đơn hàng',
            },
        ),
    ]
